#! /bin/sh
### BEGIN INIT INFO
# Provides:          katana_bridge
# Required-Start:    mountkernfs
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Setup /var/run/katana directory
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start() {
    [ -d /var/run/katana ] || mkdir /var/run/katana
    if [ -z "$(ls -A -- "/var/run/katana")" ]; then
        touch /var/run/katana/katana_0000
    fi
}

case "$1" in
    start)
	do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop|status)
        # No-op
        exit 0
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
